version: '2'
services:

    # https://elk-docker.readthedocs.io/
    elk:
        image: sebp/elk
        ports:
            - "5601:5601"  # Kibana
            - "9200:9200"  # Elastic
            - "5044:5044"  # Logstash / Beats

    # https://www.elastic.co/guide/en/apm/server/current/getting-started-apm-server.html
    apm-server:
        image: store/elastic/apm-server:7.17.2
        ports:
            - "8200:8200"  # APM Server
        command: ./apm-server -e -E output.elasticsearch.hosts=elk:9200 -E apm-server.host=0.0.0.0:8200
